### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by ghost** [n00py/WPForce#15]
Now the brute force will begin!  >:)
HTTP Error 400: Bad Request - Try reducing Thread count 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wpforce.py", line 66, in worker
    PasswordAttempt(user,password,url,thread_no,verbose,debug,agent)
  File "wpforce.py", line 164, in PasswordAttempt
    if args.verbose is True or args.debug is True:
NameError: global name 'args' is not defined

HTTP Error 400: Bad Request - Try reducing Thread count 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wpforce.py", line 66, in worker
    PasswordAttempt(user,password,url,thread_no,verbose,debug,agent)
  File "wpforce.py", line 164, in PasswordAttempt
    if args.verbose is True or args.debug is True:
NameError: global name 'args' is not defined

dont understart why this is happening?

**Comment by r63b** [comment]
Did you ever find out the problem?
