### ISSUE TITLE
Exception in thread Thread

### ISSUE THREAD

**Issue by ekasyahwan** [n00py/WPForce#7]
WAF or security plugin likely in use
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wpforce.py", line 63, in worker
    PasswordAttempt(user,password,url,thread_no,verbose,debug,agent)
  File "wpforce.py", line 155, in PasswordAttempt
    total = len(passlist)
NameError: global name 'passlist' is not defined

Traceback (most recent call last):
  File "wpforce.py", line 213, in <module>
    main()
  File "wpforce.py", line 203, in main
    time.sleep(0.1)

**Comment by n00py** [comment]
Can you post the command you ran as well?  Thanks.

**Comment by a1tem** [comment]
Hi, I have the same issue here 
timed out - Try reducing Thread count 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wpforce.py", line 63, in worker
    PasswordAttempt(user,password,url,thread_no,verbose,debug,agent)
  File "wpforce.py", line 165, in PasswordAttempt
    if args.verbose is True or args.debug is True:
NameError: global name 'args' is not defined

And process fails
I've tried to run python wpforce.py -i usr.txt -w password.txt -u "http://*****.com"  -t 2 -v

**Comment by n00py** [comment]
The website probably is shunning you after a certain number of attempts.  If you are in control of the webserver that is being targeted, can you confirm that there isn't any WAF or security plug-in running?

**Comment by s3gm3nt4ti0nf4ult** [comment]
Since those variables are readonly, try making their scope global.
